# Generated by Django 5.1.6 on 2025-03-13 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_group_options_group_students_alter_group_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("FIRST", "Первый семестр"),
                            ("SECOND", "Второй семестр"),
                            ("SUMMER", "Летний семестр"),
                            ("CUSTOM", "Индивидуальный период"),
                        ],
                        default="FIRST",
                        max_length=10,
                        verbose_name="Тип семестра",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Дата начала")),
                ("end_date", models.DateField(verbose_name="Дата окончания")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активный"),
                ),
            ],
            options={
                "verbose_name": "Семестр",
                "verbose_name_plural": "Семестры",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AddField(
            model_name="course",
            name="custom_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Индивидуальная дата начала"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Название курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Преподаватель",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="attendance.semester",
                verbose_name="Семестр",
            ),
        ),
    ]
